ARG SHIM_VERSION=15.8
FROM evren/shim-img:v${SHIM_VERSION}
RUN wget --no-verbose ${SHIM_ARCHIVE_URL} \
        -O /root/rpmbuild/SOURCES/${SHIM_ARCHIVE_FILE} && \
    echo "${SHIM_ARCHIVE_SHA256} /root/rpmbuild/SOURCES/${SHIM_ARCHIVE_FILE}" | \
        sha256sum -c
COPY sbat.evren.csv evren_securebootca_cert.der \
    shim.patches shim-find-debuginfo.sh patches/* /root/rpmbuild/SOURCES/
COPY shim-unsigned-x64.spec /root/rpmbuild/SPECS/
RUN rpmbuild -ba /root/rpmbuild/SPECS/shim-unsigned-x64.spec
RUN cp -ar /root/rpmbuild/RPMS/ /output/
