ARG SHIM_VERSION
FROM docker.io/fabricemarie/base:v${SHIM_VERSION}

ARG ATTEMPT_NO=1
ARG SHIM_ARCHIVE_URL
ARG SHIM_ARCHIVE_FILE
ARG SHIM_ARCHIVE_SHA256
ENV ATTEMPT_NO=${ATTEMPT_NO}
ENV SHIM_ARCHIVE_URL=${SHIM_ARCHIVE_URL}
ENV SHIM_ARCHIVE_FILE=${SHIM_ARCHIVE_FILE}
ENV SHIM_ARCHIVE_SHA256=${SHIM_ARCHIVE_SHA256}

RUN echo ${ATTEMPT_NO}
RUN wget --no-verbose ${SHIM_ARCHIVE_URL} \
        -O /root/rpmbuild/SOURCES/${SHIM_ARCHIVE_FILE} && \
    echo "${SHIM_ARCHIVE_SHA256} /root/rpmbuild/SOURCES/${SHIM_ARCHIVE_FILE}" | \
        sha256sum -c
COPY sbat.evren.csv evren_securebootca_cert.der \
    shim.patches shim-find-debuginfo.sh patches/* evren_dbx.esl /root/rpmbuild/SOURCES/
COPY shim-unsigned-x64.spec /root/rpmbuild/SPECS/
RUN rpmbuild -ba /root/rpmbuild/SPECS/shim-unsigned-x64.spec
CMD cp -ar /root/rpmbuild/RPMS/ /output/
